### ISSUE TITLE
株価分析のアプローチ改善の検討

### ISSUE THREAD

**Issue by TorlenBuffet** [182001a/stock_price_prediction#1]
株価の動きはどこまで予測できるか分からないが、複雑な要素が絡まりすぎて完全に予測することはタイムマシンがない限り非可能であると思われる。株価予測というアプローチより、株価が上下する局面（優位性または条件）を分析し、RR=2:1で実際にトレードするように深層強化学習を組み込むとビジネスプランとしては有効だと思う。

あと、株のロウソク足に関する情報をスクレイピングしているが、株はファンダメンタル要素が強く、「需要ある産業なのか」「新規事業が当たりそうか」などの変数を加える必要がある。四季報などのスクレイピングも行ってみた方が良い。

以上のことを検討してみないか？

**Comment by 182001a** [comment]
タイムマシンができたら通貨そのものの存在価値がなくなるな(´ω｀*)

**Comment by TorlenBuffet** [comment]
突っ込むとこそこじゃねえよ
